# Generated by Django 4.2.11 on 2025-08-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
